-- Add new fields to projects table
ALTER TABLE projects 
ADD COLUMN IF NOT EXISTS visual_style TEXT,
ADD COLUMN IF NOT EXISTS user_notes TEXT,
ADD COLUMN IF NOT EXISTS uploaded_files JSONB DEFAULT '[]'::jsonb;

-- Add new fields to scenes table
ALTER TABLE scenes
ADD COLUMN IF NOT EXISTS is_generated BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS generation_status JSONB DEFAULT '{"script": "pending", "image": "pending", "video": "pending"}'::jsonb;

-- Comment on columns
COMMENT ON COLUMN projects.visual_style IS 'User defined visual style direction for the project';
COMMENT ON COLUMN projects.user_notes IS 'Additional notes or requirements from the user';
COMMENT ON COLUMN projects.uploaded_files IS 'Array of file references uploaded by the user';
COMMENT ON COLUMN scenes.is_generated IS 'Whether the scene was generated by AI (true) or manually added (false)';
COMMENT ON COLUMN scenes.generation_status IS 'Track status of individual generation steps for this scene';
